# Generated by Django 4.0.4 on 2022-06-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDictionary', '0002_alter_tblsearchcount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsearchcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
