version: "3.9"

services:
  db:
    image: postgres:alpine3.16
    environment:
      - POSTGRES_DB=DbDictionary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    ports:
      - "5432:5432"
  web:
    volumes:
      - static:/static
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  static: